# Generated by Django 2.1.1 on 2018-09-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='route',
            name='applies_to',
            field=models.ManyToManyField(blank=True, related_name='_route_applies_to_+', to='game.Character', verbose_name='van toepassing op'),
        ),
        migrations.AlterField(
            model_name='screentype',
            name='type',
            field=models.PositiveIntegerField(choices=[(10, 'Keuze (geel)'), (11, 'Willekeurige keuze'), (20, 'Actie (groen)'), (30, 'Locatie (blauw)'), (40, 'Mededeling (rood)'), (50, 'Gesprek (oranje)')], unique=True, verbose_name='soort'),
        ),
    ]
