# Generated by Django 2.1.1 on 2018-09-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20180925_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='color',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
