# Generated by Django 2.1.1 on 2018-09-25 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_character_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='routes',
        ),
        migrations.AddField(
            model_name='screentype',
            name='color',
            field=models.CharField(blank=True, max_length=16, verbose_name='kleur'),
        ),
        migrations.AlterField(
            model_name='character',
            name='color',
            field=models.CharField(blank=True, max_length=16, verbose_name='kleur'),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='game.Screen', verbose_name='van'),
        ),
    ]
