# Generated by Django 2.1.1 on 2018-10-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180925_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('background_image', models.ImageField(blank=True, upload_to='', verbose_name='achtergrondafbeelding')),
            ],
            options={
                'verbose_name': 'locatie',
                'verbose_name_plural': 'locaties',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='screen',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Location', verbose_name='locatie'),
        ),
    ]
