# Generated by Django 2.1.1 on 2018-10-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20181003_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='achtergrondafbeelding'),
        ),
    ]
