# Generated by Django 2.1.1 on 2018-10-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_screen_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='received',
            field=models.BooleanField(default=False, verbose_name='ontvangen bericht'),
        ),
    ]
