# Generated by Django 2.1.1 on 2018-10-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_message_received'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['position'], 'verbose_name': 'bericht', 'verbose_name_plural': 'berichten'},
        ),
        migrations.AlterModelOptions(
            name='screen',
            options={'ordering': ['id'], 'verbose_name': 'scherm', 'verbose_name_plural': 'schermen'},
        ),
        migrations.AddField(
            model_name='message',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='positie'),
        ),
    ]
