# Generated by Django 2.1.1 on 2018-10-04 18:56

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20181004_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='naam')),
                ('color', colorfield.fields.ColorField(max_length=18, verbose_name='kleurcode')),
            ],
            options={
                'verbose_name': 'kleur',
                'verbose_name_plural': 'kleuren',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='screentype',
            name='background_image',
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, help_text='upload hier een PNG afbeelding met transparante achtergrond', upload_to='', verbose_name='afbeelding'),
        ),
        migrations.AddField(
            model_name='screen',
            name='image',
            field=models.ImageField(blank=True, help_text='deze afbeelding wordt alléén getoond op actieschermen', upload_to='', verbose_name='afbeelding'),
        ),
        migrations.AlterField(
            model_name='screentype',
            name='color',
            field=models.CharField(blank=True, max_length=16, verbose_name='kleurcode (in de graaf)'),
        ),
        migrations.AddField(
            model_name='location',
            name='background_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='game.Color', verbose_name='achtergrondkleur'),
        ),
        migrations.AddField(
            model_name='location',
            name='foreground_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='game.Color', verbose_name='voorgrondkleur'),
        ),
        migrations.AddField(
            model_name='screen',
            name='background_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='game.Color', verbose_name='achtergrondkleur'),
        ),
        migrations.AddField(
            model_name='screen',
            name='foreground_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='game.Color', verbose_name='voorgrondkleur'),
        ),
        migrations.AddField(
            model_name='screentype',
            name='background_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='game.Color', verbose_name='achtergrondkleur'),
        ),
        migrations.AddField(
            model_name='screentype',
            name='foreground_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='game.Color', verbose_name='voorgrondkleur'),
        ),
    ]
