# Generated by Django 2.1.1 on 2018-10-04 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20181004_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.ScreenType', verbose_name='type'),
            preserve_default=False,
        ),
    ]
