# Generated by Django 2.1.1 on 2018-10-24 10:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20181004_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='emoji',
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, help_text='upload hier een PNG afbeelding met transparante achtergrond', upload_to='', verbose_name='afbeelding'),
        ),
        migrations.AddField(
            model_name='character',
            name='intro',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='introductietekst'),
        ),
    ]
