# Generated by Django 2.1.1 on 2018-10-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20181024_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='active',
            field=models.BooleanField(default=True, verbose_name='actief'),
        ),
    ]
