# Generated by Django 2.1.1 on 2018-10-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_screen_text_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='location',
            name='foreground_color',
        ),
        migrations.RemoveField(
            model_name='screen',
            name='location',
        ),
        migrations.AlterField(
            model_name='screen',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='afbeelding'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
