# Generated by Django 2.1.1 on 2018-10-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20181025_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='emoji',
            field=models.ImageField(blank=True, help_text='Dit is het pictogram van dit karakter op het keuzescherm', upload_to='', verbose_name='afbeelding'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, help_text='Dit is de afbeelding die wordt getoond nadat de speler het karakter heeft gekozen', upload_to='', verbose_name='afbeelding'),
        ),
    ]
