# Generated by Django 2.1.1 on 2018-10-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20181025_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='button_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='game.Color', verbose_name='buttonkleur'),
        ),
    ]
