# Generated by Django 2.1.1 on 2018-11-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_screen_button_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='tekst op de "Verder"-knop'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='button_color',
            field=models.ForeignKey(blank=True, help_text='wordt nu niet gebruikt', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='game.Color', verbose_name='buttonkleur'),
        ),
    ]
