# Generated by Django 2.1.1 on 2018-12-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_route_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='afbeelding'),
        ),
        migrations.AlterField(
            model_name='screentype',
            name='type',
            field=models.PositiveIntegerField(choices=[(5, 'Introscherm'), (10, 'Keuze (geel)'), (11, 'Willekeurige keuze'), (20, 'Actie (groen)'), (30, 'Locatie (blauw)'), (40, 'Mededeling (rood)'), (50, 'Gesprek (oranje)')], unique=True, verbose_name='soort'),
        ),
    ]
