# Generated by Django 2.1.1 on 2018-12-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20181213_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='first_screen',
        ),
        migrations.RemoveField(
            model_name='route',
            name='applies_to',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
