# Generated by Django 2.1.1 on 2019-02-11 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20190109_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_enabled_if', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Route', verbose_name='Als de speler deze keuze ooit heeft gemaakt')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='game.Route')),
            ],
            options={
                'verbose_name': 'conditie',
                'verbose_name_plural': 'condities',
            },
        ),
    ]
