# Generated by Django 2.1.1 on 2019-02-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_remove_route_only_enabled_if'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['pk'], 'verbose_name': 'conditie', 'verbose_name_plural': 'condities'},
        ),
    ]
