# Generated by Django 2.1.1 on 2019-02-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_auto_20190211_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='video',
        ),
    ]
