# Generated by Django 2.1.1 on 2019-02-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_auto_20190211_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='screentype',
            name='audio',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
