# Generated by Django 2.1.1 on 2019-02-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_screentype_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='loop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='screentype',
            name='loop',
            field=models.BooleanField(default=True),
        ),
    ]
