# Generated by Django 2.1.1 on 2019-02-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_auto_20190211_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='image_desktop',
            field=models.ImageField(blank=True, upload_to='', verbose_name='afbeelding desktop'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='afbeelding mobiel'),
        ),
        migrations.AlterField(
            model_name='screentype',
            name='type',
            field=models.PositiveIntegerField(choices=[(5, 'Introscherm'), (10, 'Keuze (geel)'), (11, 'Willekeurige keuze'), (20, 'Actie (groen)'), (30, 'Locatie (blauw)'), (40, 'Mededeling (rood)'), (50, 'Gesprek (oranje)'), (60, 'Video (grijs)'), (70, 'Level (bruin)')], unique=True, verbose_name='soort'),
        ),
    ]
