# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 18:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.PositiveIntegerField()),
                ('content', models.TextField(verbose_name='inhoud')),
            ],
            options={
                'ordering': ['parameter'],
                'verbose_name': 'Parameter',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('menu', models.BooleanField(default=True, verbose_name='zichtbaar in het menu')),
            ],
            options={
                'verbose_name_plural': 'Pagina’s',
                'verbose_name': 'Pagina',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(blank=True, verbose_name='positie')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Normale sectie'), (2, 'Programmasectie'), (3, 'Footer')], default=1, verbose_name='soort sectie')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='titel')),
                ('contents', ckeditor.fields.RichTextField(blank=True, verbose_name='inhoud')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='kafka.Page', verbose_name='pagina')),
            ],
            options={
                'ordering': ['position'],
                'verbose_name': 'sectie',
            },
        ),
    ]
