# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='type',
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, help_text='Laat dit veld leeg voor de homepage', unique=True, verbose_name='URL'),
        ),
    ]
