# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0002_auto_20170911_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('normal', 'Normale sectie'), ('program', 'Programmasectie'), ('footer', 'Footer')], default=1, max_length=32, verbose_name='soort sectie'),
        ),
    ]
