# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 20:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0003_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='datum')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
            ],
            options={
                'verbose_name_plural': 'Evenementen',
                'verbose_name': 'Evenement',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='datum')),
                ('contents', ckeditor.fields.RichTextField(blank=True, verbose_name='inhoud')),
                ('link', models.URLField(verbose_name='bron')),
            ],
            options={
                'verbose_name_plural': 'Nieuwsberichten',
                'verbose_name': 'Nieuwsbericht',
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='datum')),
                ('documentation', ckeditor.fields.RichTextField(blank=True, verbose_name='documentatie')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kafka.Event')),
            ],
            options={
                'verbose_name': 'Werksessie',
            },
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'ordering': ['parameter'], 'verbose_name': 'Configuratieparameter'},
        ),
    ]
