# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0004_auto_20170911_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='date',
        ),
        migrations.AddField(
            model_name='worksession',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='titel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worksession',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kafka.Event', verbose_name='evenement'),
        ),
    ]
