# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0005_auto_20170911_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titel')),
                ('slug', models.SlugField()),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='inhoud')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube of Vimeo link')),
                ('worksession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentations', to='kafka.WorkSession', verbose_name='werk sessie')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Documentaties',
                'verbose_name': 'Documentatie',
            },
        ),
        migrations.CreateModel(
            name='DocumentationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255, verbose_name='bijschrift')),
                ('image', models.ImageField(upload_to='')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafka.Documentation')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='afbeelding'),
        ),
        migrations.AddField(
            model_name='section',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube, Vimeo, of SoundCloud link'),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, help_text='Plak hier een optionele hyperlink naar het originele bericht', verbose_name='bron'),
        ),
    ]
