# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0006_auto_20170914_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentationimage',
            options={'ordering': ['caption'], 'verbose_name': 'Foto', 'verbose_name_plural': 'Foto’s'},
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='documentation',
        ),
        migrations.AddField(
            model_name='worksession',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='beschrijving'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='slug',
            field=models.SlugField(help_text='Deze text wordt gebruik in de URL naar deze documentatie'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='worksession',
            field=models.ForeignKey(blank=True, help_text='Kies hier een optionele werksessie waar deze documentatie bij hoort', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentations', to='kafka.WorkSession', verbose_name='werksessie'),
        ),
    ]
