# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0007_auto_20170914_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='begin_time',
            field=models.TimeField(blank=True, null=True, verbose_name='begintijd'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='datum'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='eindtijd'),
        ),
    ]
