# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:49
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0008_auto_20170914_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webtext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.PositiveIntegerField(choices=[(1, 'Homepage tekst')])),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='inhoud')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='afbeelding')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, help_text='Plak hier een YouTube, Vimeo, of SoundCloud link')),
            ],
            options={
                'verbose_name': 'Webtekst',
                'ordering': ['parameter'],
                'verbose_name_plural': 'Webteksten',
            },
        ),
    ]
