# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0010_auto_20170914_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='slug',
            field=models.SlugField(help_text='Deze text wordt gebruik in de URL naar deze documentatie', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='slug',
            field=models.SlugField(help_text='Deze text wordt gebruik in de URL naar deze documentatie', unique=True),
        ),
    ]
