# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0012_auto_20170914_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='naam')),
                ('image', models.ImageField(upload_to='', verbose_name='afbeelding')),
            ],
            options={
                'verbose_name_plural': 'Emoji',
            },
        ),
        migrations.AlterField(
            model_name='documentationimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='afbeelding'),
        ),
    ]
