# Generated by Django 2.1.1 on 2018-10-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka', '0014_emoji_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtext',
            name='parameter',
            field=models.PositiveIntegerField(choices=[(1, 'Homepage tekst'), (50, 'Game intro tekst'), (100, 'Footer tekst')]),
        ),
    ]
